include:
  - project: 'Recetox/mass-spectrometry/galaxy-tools-deployment'
    file: '/pipeline_templates/.gitlab-ci-docker.yml'
  - project: 'Recetox/mass-spectrometry/galaxy-tools-deployment'
    file: '/pipeline_templates/.gitlab-ci-toolshed.yml'
  - project: 'Recetox/mass-spectrometry/galaxy-tools-deployment'
    file: '/pipeline_templates/.gitlab-ci-galaxy.yml'

stages:
  - docker_build
  - toolshed_upload
  - galaxy_deploy

variables:
  TOOL_PANEL_SECTION_LABEL: "Annotation"

docker-build-test:
  extends: .docker-build-test

docker-build-release:
  extends: .docker-build-release

testing-toolshed-instance-upload:
  extends: .testing-toolshed-instance-upload

testing-instance-galaxy-deploy:
  extends: .testing-instance-galaxy-deploy

umsa-toolshed-instance-upload:
  extends: .umsa-toolshed-instance-upload

umsa-instance-galaxy-deploy:
  extends: .umsa-instance-galaxy-deploy
