name: recetox-xmsannotator-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base >= 3.5
  - r-devtools
  - boost-cpp
  - r-biocmanager
  - r-flashclust
  - r-plyr
  - r-wgcna
  - r-tidyr
  - r-purrr
  - r-tibble
  - r-dplyr >= 1.0.0
  - r-rcpp >= 0.11.0
  - r-arrow >= 3.0.0
  - bioconductor-rhdf5
  - r-data.table
  - r-testthat >= 3.0.0
  - r-readr
  - r-pastecs
  - r-rlist
  - r-rann
  - r-gplots
  - r-devtools
  - r-entropy
  - r-rcdk
  - r-patrick
