name: recetox-xmsannotator-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base >= 4.1.1
  - r-devtools >= 2.4.2
  - boost-cpp
  - r-biocmanager >= 1.30.16
  - r-flashclust >= 1.01_2
  - r-plyr >= 1.8.6
  - r-wgcna >= 1.69
  - r-tidyr >= 1.1.4
  - r-purrr >= 0.3.4
  - r-tibble >= 3.1.5
  - r-dplyr >= 1.0.0
  - r-rcpp >= 0.11.0
  - r-arrow >= 3.0.0
  - bioconductor-rhdf5
  - r-data.table >= 1.14.2
  - r-testthat >= 3.0.0
  - r-readr >= 2.0.2
  - r-pastecs >= 1.3.21
  - r-rlist >= 0.4.6.2
  - r-rann >= 2.6.1
  - r-gplots
  - r-entropy >= 1.3.1
  - r-rcdk >= 3.5.0
  - r-patrick >= 0.1.0
  - r-datacomparer >= 0.1.3
  - bioconductor-rdisop

